### ISSUE TITLE
Fix cramped report layout for single reports

### ISSUE THREAD

**Issue by matejkepes** [matejkepes/review-master#3]
## Problem Statement
Client portal reports appear cramped on the left side when viewing a single report. The grid layout is designed for multiple reports but doesn't adapt properly for single-report scenarios.

## Root Cause
**Backend**: `rm_client_portal/shared/monthly_report_template.go:162` - CSS grid uses `auto-fill` which creates empty columns
```css
grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
```
**Frontend**: Multiple nested containers (MainLayout → ReportViewPage → iframe → template) compound the constraint issue

## Dependencies
- Consider creating shared folder in monorepo for layouts used by both `google_my_business` and `rm_client_portal`

## Acceptance Criteria

**Must Have (Critical):**
- [ ] Single reports expand to use full available width
- [ ] Multi-report layouts continue to work correctly
- [ ] Fix works across all modern browsers
- [ ] Mobile responsive behavior maintained
- [ ] No layout breaking at different viewport sizes

**Nice to Have:**
- [ ] Dynamic layout based on report count
- [ ] Optimized container nesting
- [ ] Improved mobile experience
- [ ] Better iframe width utilization

## Technical Requirements

**Quick Fix - Grid Optimization:**
```css
.location-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); /* Change from auto-fill */
  gap: 20px;
}
```

**Responsive Enhancement:**
```css
@media (max-width: 800px) {
  .location-cards {
    grid-template-columns: 1fr;
  }
}

.container {
  max-width: min(1200px, 100vw - 32px);
}
```

## Test Cases
```bash
# Test Case 1: Single report display
1. Load report with 1 location
2. Verify report expands to full container width
3. Check no empty space on right side
4. Confirm executive summary cards align properly

# Test Case 2: Multiple reports
1. Load report with 3-5 locations
2. Verify grid creates appropriate columns
3. Check spacing between cards is consistent
4. Confirm no overflow or cramping

# Test Case 3: Responsive behavior
1. Test at viewport widths: 320px, 768px, 1024px, 1440px
2. Verify single column on mobile
3. Check multi-column on desktop
4. Confirm no horizontal scrolling

# Test Case 4: Cross-browser
1. Test in Chrome, Firefox, Safari
2. Verify layout consistency
3. Check grid behavior matches across browsers
```

## Files to Modify
- `rm_client_portal/shared/monthly_report_template.go` (CSS grid fixes)
- `google_my_business/shared/monthly_report_template.go` (if duplicate exists)
- Consider creating shared layout folder for both services
